# Project-wide Gradle settings.
# For more details on how to configure your build, see
# http://www.gradle.org/docs/current/userguide/build_the_project.html#sec:gradle_properties_and_the_command_line

# Enables AndroidX
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Specifies the JVM arguments used for the Gradle Daemon.
# The setting is particularly useful for configuring JVM memory settings for build performance.
# Default value: -Xmx512m "-XX:MaxMetaspaceSize=256m"
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
